[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor="#007bff"
backgroundColor="#f5f7fa"
secondaryBackgroundColor="#ffffff"
textColor="#2c3e50"
font="sans serif"